{{- if .Values.route.enabled -}}
{{- $fullName := include "mcp-victoriatraces.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels: {{ include "mcp-victoriatraces.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.route.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.hostnames }}
  hostnames: {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.route.rules }}
    {{- with .matches }}
    - matches: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters: {{ toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
{{- end }}
